-- V1__initial_schema.sql
-- Schema baseline extraido diretamente do PostgreSQL (Neon) em 12/06/2026.
-- Hibernate 7 / JPA 3.2 / Spring Boot 4.0.0
--
-- PKs: BIGINT GENERATED BY DEFAULT AS IDENTITY (confirmado via information_schema)
-- Timestamps: timestamp without time zone (sem precisao explicita)
-- installment_amount: numeric(38,2) (padrao JPA 3.2 para BigDecimal sem @Column precision)
--
-- ESTRATEGIA DE DEPLOY:
--   Banco existente: flyway.baseline-on-migrate=true + baseline-version=1
--     -> Flyway marca como V1 sem executar este script
--   Banco novo: Flyway executa este script integralmente

CREATE TABLE IF NOT EXISTS user_account (
    id_user   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_user CHARACTER VARYING(255),
    email     CHARACTER VARYING(255) UNIQUE,
    password  CHARACTER VARYING(255),
    role      CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS account (
    id_account        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_account      CHARACTER VARYING(255),
    photo_url_account CHARACTER VARYING(255),
    id_user           BIGINT REFERENCES user_account(id_user)
);

CREATE TABLE IF NOT EXISTS category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       CHARACTER VARYING(255),
    type       CHARACTER VARYING(255),
    account_id BIGINT REFERENCES account(id_account) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bill (
    id_bill             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description         CHARACTER VARYING(255) NOT NULL,
    emission            DATE                   NOT NULL,
    maturity            DATE                   NOT NULL,
    installment_amount  NUMERIC(38, 2)         NOT NULL,
    parcel_number       INTEGER,
    current_installment INTEGER,
    periodicity         CHARACTER VARYING(255) NOT NULL,
    status              CHARACTER VARYING(255) NOT NULL,
    category_id         BIGINT NOT NULL REFERENCES category(id),
    account_id          BIGINT NOT NULL REFERENCES account(id_account),
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    paid_at             TIMESTAMP,
    received_at         TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checklist_item (
    id_checklist_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description       CHARACTER VARYING(255) NOT NULL,
    due_day           INTEGER                NOT NULL,
    active            BOOLEAN                NOT NULL,
    account_id        BIGINT NOT NULL REFERENCES account(id_account)
);
