-- V7__checklist_completion.sql
-- Cria tabela checklist_completion para persistir o estado de conclusão mensal
-- de cada ChecklistItem por mês. Um registro = item concluído naquele mês.
-- Ausência de registro = item pendente. Idempotência garantida pela UNIQUE constraint.

CREATE TABLE checklist_completion (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_item_id BIGINT      NOT NULL
        REFERENCES checklist_item(id_checklist_item) ON DELETE CASCADE,
    month             VARCHAR(7)  NOT NULL,
    completed_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uq_checklist_completion UNIQUE (checklist_item_id, month)
);
