-- V9__password_reset_token.sql
-- Tabela de tokens para recuperacao de senha.
-- ON DELETE CASCADE garante limpeza automatica quando o usuario for excluido (LGPD).
-- Indice em token: lookup O(1) por valor do token.
-- Indice em id_user: suporte ao cascade + listagem de tokens por usuario.

CREATE TABLE IF NOT EXISTS password_reset_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      CHARACTER VARYING(255) NOT NULL UNIQUE,
    id_user    BIGINT NOT NULL REFERENCES user_account(id_user) ON DELETE CASCADE,
    expires_at TIMESTAMP NOT NULL,
    used       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_token
    ON password_reset_token (token);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_id_user
    ON password_reset_token (id_user);
